CREATE TABLE IF NOT EXISTS documents (
    url TEXT PRIMARY KEY,
    name TEXT,
    description TEXT,
    error BOOLEAN DEFAULT FALSE,
    
    cleaned_html TEXT,
    crawl_success BOOLEAN,
    crawl_error_message TEXT,
    crawl_error_primary TEXT,
    crawl_error_fallback TEXT,
    crawl_mode TEXT,
    crawl_url_type TEXT,
    cleaned_html_length INT,
    crawl_suspect BOOLEAN,
    crawl_attempt_count INT,
    crawl_primary_success BOOLEAN,
    crawl_fallback_used BOOLEAN,
    crawl_started_at_utc TIMESTAMP,
    crawl_finished_at_utc TIMESTAMP,
    crawl_elapsed_seconds FLOAT,
    crawler_version_hint TEXT,
    debug_requested_url TEXT,
    debug_result_url TEXT,
    debug_status_code INT,
    debug_match_method TEXT,
    debug_batch_id INT,
    
    stage4_success BOOLEAN,
    stage4_error_message TEXT,
    stage4_model_name TEXT,
    stage4_prompt_version TEXT,
    stage4_processed_at_utc TIMESTAMP,
    stage4_input_html_length INT,
    stage4_llm_input_html_length INT,
    stage4_html_was_truncated BOOLEAN,
    stage4_agent_final_message TEXT,

    is_relevant BOOLEAN,
    can_extract_markdown BOOLEAN,
    relevance_reason TEXT,
    document_kind TEXT,
    contains_main_text BOOLEAN,
    contains_incident_information BOOLEAN,
    has_timeline BOOLEAN,
    has_root_cause BOOLEAN,
    has_impact_description BOOLEAN,
    has_resolution_or_mitigation BOOLEAN,
    has_action_items_or_lessons_learned BOOLEAN,
    language TEXT,
    relevance_confidence FLOAT,

    stage5_success BOOLEAN,
    stage5_error_message TEXT,
    stage5_model_name TEXT,
    stage5_prompt_version TEXT,
    stage5_processed_at_utc TIMESTAMP,
    stage5_input_html_length INT,
    stage5_llm_input_html_length INT,
    stage5_html_was_truncated BOOLEAN,
    stage5_agent_final_message TEXT,
    markdown_length INT,
    markdown_content TEXT,

    stage6_success BOOLEAN,
    stage6_error_message TEXT,
    stage6_model_name TEXT,
    stage6_prompt_version TEXT,
    stage6_processed_at_utc TIMESTAMP,
    stage6_input_markdown_length INT,
    stage6_llm_input_markdown_length INT,
    stage6_markdown_was_truncated BOOLEAN,
    stage6_agent_final_message TEXT,

    company TEXT,
    incident_date DATE,
    short_description TEXT,
    incident_categories JSONB,
    tech_stack JSONB,
    infrastructure JSONB,
    key_terms JSONB,
    symptoms TEXT,
    root_cause TEXT,
    resolution TEXT,
    lessons_learned TEXT,
    metadata_confidence FLOAT,

    qdrant_point_id UUID,
    tech_stack_text TEXT,
    key_terms_text TEXT,
    embedding_text TEXT,

    status TEXT DEFAULT 'new',
    content_hash TEXT,

    discovered_at TIMESTAMP DEFAULT NOW(),
    processed_at TIMESTAMP,
    updated_at TIMESTAMP DEFAULT NOW(),
    retry_count INT DEFAULT 0,
    last_error TEXT,
    last_error_at TIMESTAMP,

    CONSTRAINT valid_status CHECK (status IN ('new', 'in_progress', 'error', 'success', 'skipped'))
);

COMMENT ON COLUMN documents.status IS 'new | in_progress | error | success | skipped';
COMMENT ON COLUMN documents.document_kind IS 'postmortem | incident_report | status_update | irrelevant | unknown';